# Generated by Django 5.1.6 on 2025-05-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0004_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
