# Generated by Django 5.2 on 2025-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0005_facultyassignment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester'), ('Summer', 'Summer Semester')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('year', 'semester', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'course', 'year_level')},
        ),
    ]
