# Generated by Django 5.1.6 on 2025-05-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0006_alter_room_slug_alter_schedule_semester_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('year', 'semester')},
        ),
    ]
