# Generated by Django 5.1.6 on 2025-05-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0007_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
