# Generated by Django 5.1.6 on 2025-05-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0008_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
