# Generated by Django 5.1.6 on 2025-05-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0009_alter_schedule_year'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('section', 'subject'), name='unique_section_subject'),
        ),
    ]
