# Generated by Django 5.2 on 2025-05-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0006_alter_schedule_semester_alter_schedule_year_and_more'),
        ('hrapp', '0009_alter_schedule_year'),
    ]

    operations = [
    ]
