# Generated by Django 5.1.6 on 2025-05-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0010_schedule_unique_section_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
