# Generated by Django 5.2 on 2025-05-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0010_merge_20250526_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
