# Generated by Django 5.1.6 on 2025-05-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0016_alter_program_code_alter_program_professors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
