# Generated by Django 5.2.1 on 2025-06-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0019_timestamp_evaluation_timestamp_time_records'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='time_records',
            new_name='time_record',
        ),
    ]
