# Generated by Django 5.1.6 on 2025-06-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0022_evaluation_ai_feedback_alter_timestamp_time_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_section_subject',
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('program', 'section', 'subject'), name='unique_section_subject'),
        ),
    ]
