# Generated by Django 5.1.6 on 2025-06-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0023_remove_schedule_unique_section_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Soft delete flag', null=True),
        ),
    ]
