# Generated by Django 5.1.6 on 2025-06-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0024_alter_user_is_deleted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'program', 'year_level'), name='unique_section_program_year'),
        ),
    ]
