# Generated by Django 5.1.6 on 2025-06-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0026_section_slug_alter_section_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='section',
            name='unique_section_program_year',
        ),
    ]
