# Generated by Django 5.1.6 on 2025-06-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0027_remove_section_unique_section_program_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
    ]
