# Generated by Django 5.2.2 on 2025-06-24 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0028_alter_section_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentevaluation',
            name='user_professor',
        ),
        migrations.RemoveField(
            model_name='studentevaluationresponse',
            name='schedule',
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.schedule'),
        ),
    ]
