# Generated by Django 5.2.2 on 2025-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0029_remove_studentevaluation_user_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentevaluation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
