# Generated by Django 5.1.6 on 2025-06-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0031_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
