# Generated by Django 5.1.6 on 2025-07-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0033_remove_studentevaluationquestion_student_evaluation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentevaluationresponse',
            unique_together={('user', 'student_evaluation', 'student_eval_question')},
        ),
    ]
