# Generated by Django 5.1.6 on 2025-07-08 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0034_alter_studentevaluationresponse_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dean', models.ForeignKey(limit_choices_to={'role': 'Dean'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties_as_dean', to=settings.AUTH_USER_MODEL)),
                ('evaluations', models.ManyToManyField(blank=True, related_name='faculties', to='hrapp.evaluation')),
                ('professors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Professor'}, related_name='faculties_as_professor', to=settings.AUTH_USER_MODEL)),
                ('student_evaluations', models.ManyToManyField(blank=True, related_name='faculties', to='hrapp.studentevaluation')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='hrapp.faculty'),
        ),
    ]
