# Generated by Django 5.1.6 on 2025-07-08 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0035_faculty_program_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties_as_dean', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='professors',
            field=models.ManyToManyField(blank=True, related_name='faculties_as_professor', to=settings.AUTH_USER_MODEL),
        ),
    ]
