# Generated by Django 5.1.6 on 2025-08-05 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0036_alter_faculty_dean_alter_faculty_professors'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevaluation',
            name='canonical_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrapp.schedule'),
        ),
    ]
