# Generated by Django 5.1.6 on 2025-08-05 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0037_studentevaluation_canonical_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentevaluation',
            name='canonical_id',
        ),
        migrations.AddField(
            model_name='studentevaluationquestion',
            name='canonical_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
