# Generated by Django 5.2.5 on 2025-08-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0039_alter_studentevaluationresponse_student_eval_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScatterPlotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_rate', models.FloatField(blank=True, null=True)),
                ('year', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], max_length=20)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('Summer', 'Summer')], max_length=20)),
            ],
        ),

        migrations.AlterUniqueTogether(
            name='scatterplotanalytics',
            unique_together={('year', 'semester', 'retention_rate')},
        ),
    ]
