# Generated by Django 5.2.5 on 2025-08-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0040_scatterplotanalytics_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentevaluation',
            name='unique_schedule_import_questions',
        ),
    ]
