# Generated by Django 5.2.5 on 2025-08-15 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0041_remove_studentevaluation_unique_schedule_import_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatterplotanalytics',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
