# Generated by Django 5.2.5 on 2025-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0042_scatterplotanalytics_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
