# Generated by Django 5.2.5 on 2025-08-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0043_alter_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
