# Generated by Django 5.1.6 on 2025-08-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0044_alter_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevaluationresponse',
            name='sentiment_score',
            field=models.JSONField(blank=True, help_text='DistilBERT sentiment analysis results: {label, score, points}', null=True),
        ),
    ]
