# Generated by Django 5.1.6 on 2025-08-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0045_add_sentiment_score_to_response'),
    ]


