# Generated by Django 5.1.6 on 2025-08-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0046_alter_scatterplotanalytics_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scatterplotanalytics',
            unique_together={('year', 'semester', 'retention_rate')},
        ),
    ]
